### ISSUE TITLE
{"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."}"

### ISSUE THREAD

**Issue by sagarjainubuy** [Ekman/aws-ring-http-signer#11]
{"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."}"

**Comment by Ekman** [comment]
I'll need some code in order to assist. Have you double checked your AWS credentials? It looks like you might have incorrect ones.

**Comment by sagarjainubuy** [comment]
It is working with this library - https://github.com/jeskew/amazon-es-php

**Comment by Ekman** [comment]
I see! Then I need to see some code 🙂. How are you using the library? How are you instantiating your ring client?

**Comment by Ekman** [comment]
Thanks for your feedback!

Without any further data I won't be able to assist unfortunately. I'll keep an extra eye on this in our environments to see if I can find any similar errors. Feel free to reopen this issue if the error persists. However, I need to see some code in order to assist you.
